openapi: 3.0.0
info:
  title: toys
  version: '1.0'
  description: toys api
servers:
  - url: 'http://localhost:3000'
paths:
  '/toys/{toyid}':
    parameters:
      name: toyid
      in: path
      required: true
      type: string
components:
  schemas: {}
