openapi: 3.0.0
info:
  title: toys
  version: '1.0'
  description: toys api
servers:
  - url: 'http://localhost:3000'
paths:
  '/toys/{toyid}':
    parameters:
      name: toyid
      in: path
      required: true
      type: string
    get:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '201':
          description: Created
      description: get toys
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
