openapi: 3.0.0
info:
  title: MyAPI
  version: '1.0'
  description: My APIaaaaaaaa
  contact:
    name: David Roberts
    email: dr@stoplight.io
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
